In [0]:
from sklearn.datasets import load_iris, load_diabetes,load_wine
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.metrics import r2_score,mean_squared_error
from sklearn import linear_model
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold, StratifiedKFold,cross_val_score
import numpy as np
from matplotlib import pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
from statistics import mean

In [0]:
wine = load_wine()

#Kfold
features, target = wine.data, wine.target

avg_score = []

kf = KFold(n_splits=3)
kf.get_n_splits(features)
knn = KNeighborsClassifier(n_neighbors=3)

print(kf)

for train_index, test_index in kf.split(features):
    print("\ntrain_size:", len(train_index),"\n" ,"\ntest_size", len(test_index),"\n")
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = target[train_index], target[test_index]
    
    print("\ntest_class_size:\n",pd.value_counts(y_test))
    print("\ntrain_class_size:\n",pd.value_counts(y_train))
    
    knn.fit(X_train,y_train)

    score_fold_value = knn.score(X_test,y_test)

    print("score:",score_fold_value)
    avg_score.append(score_fold_value)
    print(50*"*")
    
print("avg_mean: ", mean(avg_score))


KFold(n_splits=3, random_state=None, shuffle=False)

train_size: 118 
 
test_size 60 


test_class_size:
 0    59
1     1
dtype: int64

train_class_size:
 1    70
2    48
dtype: int64
score: 0.0
**************************************************

train_size: 119 
 
test_size 59 


test_class_size:
 1    59
dtype: int64

train_class_size:
 0    59
2    48
1    12
dtype: int64
score: 0.288135593220339
**************************************************

train_size: 119 
 
test_size 59 


test_class_size:
 2    48
1    11
dtype: int64

train_class_size:
 1    60
0    59
dtype: int64
score: 0.1864406779661017
**************************************************
avg_mean:  0.15819209039548024


In [0]:
#StratifiedKFold

avg_score = []
features, target = wine.data, wine.target

skf = StratifiedKFold(n_splits=3)
skf.get_n_splits(features,target)
knn = KNeighborsClassifier(n_neighbors=3)

print(skf)

for train_index, test_index in skf.split(features,target):
    print("\ntrain_size:", len(train_index),"\n" ,"\ntest_size", len(test_index),"\n")
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = target[train_index], target[test_index]
    
    print("\ntest_class_size:\n",pd.value_counts(y_test))
    print("\ntrain_class_size:\n",pd.value_counts(y_train))
    
    knn.fit(X_train,y_train)
    
    score_fold_value = knn.score(X_test,y_test)

    print("score:",score_fold_value)
    avg_score.append(score_fold_value)
    print(50*"*")
    
print("avg_mean: ", mean(avg_score))

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

train_size: 118 
 
test_size 60 


test_class_size:
 1    24
0    20
2    16
dtype: int64

train_class_size:
 1    47
0    39
2    32
dtype: int64
score: 0.6166666666666667
**************************************************

train_size: 119 
 
test_size 59 


test_class_size:
 1    23
0    20
2    16
dtype: int64

train_class_size:
 1    48
0    39
2    32
dtype: int64
score: 0.576271186440678
**************************************************

train_size: 119 
 
test_size 59 


test_class_size:
 1    24
0    19
2    16
dtype: int64

train_class_size:
 1    47
0    40
2    32
dtype: int64
score: 0.7966101694915254
**************************************************
avg_mean:  0.6631826741996234


In [0]:
knn = KNeighborsClassifier(n_neighbors=3)


[0.61666667 0.57627119 0.79661017]


In [0]:
%time print(cross_val_score(knn, features, target, cv=3, verbose=1))

[0.61666667 0.57627119 0.79661017]
Wall time: 28 ms


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s finished


In [0]:
%time print(cross_val_score(knn, features, target, cv=5,verbose=5))

[CV] END ................................ score: (test=0.639) total time=   0.0s
[CV] END ................................ score: (test=0.694) total time=   0.0s
[CV] END ................................ score: (test=0.667) total time=   0.0s
[CV] END ................................ score: (test=0.657) total time=   0.0s
[CV] END ................................ score: (test=0.857) total time=   0.0s
[0.63888889 0.69444444 0.66666667 0.65714286 0.85714286]
Wall time: 37 ms


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.0s finished


In [0]:
%time print(cross_val_score(knn, features, target, cv=10))

In [0]:
X_test

Out[93]: array([[1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
        3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, 1.120e+01, 1.000e+02, 2.650e+00,
        2.760e+00, 2.600e-01, 1.280e+00, 4.380e+00, 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, 1.860e+01, 1.010e+02, 2.800e+00,
        3.240e+00, 3.000e-01, 2.810e+00, 5.680e+00, 1.030e+00, 3.170e+00,
        1.185e+03],
       [1.437e+01, 1.950e+00, 2.500e+00, 1.680e+01, 1.130e+02, 3.850e+00,
        3.490e+00, 2.400e-01, 2.180e+00, 7.800e+00, 8.600e-01, 3.450e+00,
        1.480e+03],
       [1.324e+01, 2.590e+00, 2.870e+00, 2.100e+01, 1.180e+02, 2.800e+00,
        2.690e+00, 3.900e-01, 1.820e+00, 4.320e+00, 1.040e+00, 2.930e+00,
        7.350e+02],
       [1.420e+01, 1.760e+00, 2.450e+00, 1.520e+01, 1.120e+02, 3.270e+00,
        3.390e+00, 3.400e-01, 1.970e+00, 6.750e+00, 1.050e+00, 2.850e+00,
   

In [0]:
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]


In [0]:
kf = KFold(n_splits=3)
kf.get_n_splits(X)

print(kf)
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    


KFold(n_splits=3, random_state=None, shuffle=False)
TRAIN: [2 3 4 5] TEST: [0 1]


---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_2632/3636129290.py in <module>
      6 for train_index, test_index in kf.split(X):
      7     print("TRAIN:", train_index, "TEST:", test_index)
----> 8     X_train, X_test = X[train_index], X[test_index]

TypeError: unhashable type: 'numpy.ndarray'

In [0]:
wine

Out[33]: {'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [0]:
splits = 3
kf = KFold(n_splits=splits)
X = np.arange(0,12,1)
print(len(X)//splits)

for fold_nb, (train_index,test_index) in enumerate(kf.split(X)):
    print("Fold no:", fold_nb)
    print("train size:", len(train_index),"test size:",len(test_index))

4
Fold no: 0
train size: 8 test size: 4
Fold no: 1
train size: 8 test size: 4
Fold no: 2
train size: 8 test size: 4
